name: hello_clutter
description: A simple game using Clutter.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  statsfl: ^2.3.0
  clutter:
    path: ../../

dev_dependencies:
  flutter_lints: ^2.0.0